/**
 * Contact Management
 * <h3>HOW TO GENERATE API CLIENTS:</h3>java -jar <a href='https://www.sangkhim.com/api/swagger-codegen-cli-2.3.1.jar' target='_blank'>C:\\swagger-codegen-cli-2.3.1.jar</a> generate -l typescript-angular -i https://www.sangkhim.com/api/swagger.json -o C:\\generated<h3>LANGUAGES:</h3>-l typescript-angular (Angular)<br />-l javascript (React)<br />-l java (Android)<br />-l objc (Objective C)<br />-l swift4 (Swift 4)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sangkhim@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Contact {
    id?: number;
    photo?: string;
    name?: string;
    city?: string;
    tel?: string;
    email?: string;
}
